backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Featurebild", name: "img", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - name: "universal"
        label: "Startsida"
        file: "src/pages/index/index.md"
        fields:
          - {label: "Logo", name: "logo", widget: "image"}
          - label: "Extrapuffar"
            name: "boxes"
            widget: "list"
            optional: true
            fields:
              - {label: "Rubrik", name: "title", widget: "string", optional: true}
              - {label: "CTA", name: "cta", widget: "string", optional: true}
              - {label: "Länk", name: "link", widget: "relation", collection: "pages", searchFields: ["label", "name"], valueField: "label"}
      - file: "src/pages/privat/index.md"
        label: "Privat"
        name: "privat"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "privat-page"}
          - {label: "Topptitel", name: "title", widget: "string", optional: true}
          - {label: "Introtext", name: "intro", widget: "markdown", optional: true}
          - label: "CTA"
            name: "cta"
            widget: "list"
            optional: true
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
          - {label: "Erbjudanderubrik", name: "offerTitle", widget: "string", optional: true}
          - label: "Erbjudanden"
            name: "offers"
            widget: "list"
            optional: true
            fields:
              - {label: "Rubrik", name: "title", widget: "string", optional: true}
              - {label: "Text", name: "body", widget: "text", optional: true}
              - {label: "Pris", name: "price", widget: "text", optional: true}
              - label: ”USP-lista”
                name: "Listan under erbjudande"
                widget: "list"
                optional: true
                fields:
                  - {label: "Fetad text", name: "strongText", widget: "string", optional: true}
                  - {label: "text", name: "text", widget: "string", optional: true}
              - label: "CTA"
                name: "cta"
                widget: "list"
                optional: true
                fields:
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
          - {label: "Sluttext", name: "ending", widget: "markdown", optional: true}

      - file: "src/pages/foretag/index.md"
        label: "Företag"
        name: "foretag"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "foretag-page"}
          - {label: "Topptitel", name: "title", widget: "string"}
          - {label: "Introtext", name: "intro", widget: "markdown"}
          - {label: "CTA", name: "cta", widget: "string", optional: true}
          - {label: "Erbjudanderubrik", name: "offerTitle", widget: "string", optional: true}
          - label: "Erbjudanden"
            name: "offers"
            widget: "list"
            optional: true
            fields:
              - {label: "Rubrik", name: "title", widget: "string", optional: true}
              - {label: "Text", name: "body", widget: "text", optional: true}
              - label: ”USP-lista”,
                name: "usps"
                widget: "list"
                optional: true
                fields:
                  - {label: "Rubrik", name: "title", widget: "string", optional: true}
                  - {label: "Extrainfo", name: "body", widget: "string", optional: true}
          - {label: "Erbjudande CTA", name: "cta", widget: "string", optional: true}
          - label: "Extrapuffar"
            name: "boxes"
            widget: "list"
            optional: true
            fields:
              - {label: "Rubrik", name: "title", widget: "string", optional: true}
              - {label: "CTA", name: "cta", widget: "string", optional: true}
          - {label: "Sluttext", name: "ending", widget: "markdown", optional: true}

      - file: "src/pages/coacher/index.md"
        label: "Coacher"
        name: "coacher"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "coach-page"}
          - {label: "Topptitel", name: "title", widget: "string"}
          - {label: "Introtext", name: "intro", widget: "text"}
          - label: "Coacher"
            name: "coaches"
            widget: "list"
            optional: true
            fields:
              - {label: "Bild", name: "img", widget: "image", optional: true}
              - {label: "Namn", name: "title", widget: "string", optional: true}
              - {label: "USP", name: "usp", widget: "string", optional: true}
              - {label: "Text", name: "text", widget: "markdown", optional: true}
          - {label: "Sluttext", name: "ending", widget: "markdown", optional: true}
          - {label: "CTA", name: "cta", widget: "string", optional: true}

      - file: "src/pages/kontakt/index.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Topptitel", name: "title", widget: "string", optional: true}
          - {label: "Introtext", name: "intro", widget: "text", optional: true}
          - label: "Formulär"
            name: "forms"
            widget: "list"
            optional: true
            fields:
              - {label: "Kundkategori", name: "category", widget: "string", optional: true}
              - label: "Fält"
                name: "fields"
                widget: "list"
                optional: true
                fields:
                  - {label: "Namn", name: "name", widget: "string", optional: true}
                  - {label: "Placeholdertext", name: "placeholder", widget: "string", optional: true}
                  - {label: "Typ", name: "type", widget: 'select', options: ['text', 'email', 'number', 'url', 'textarea'], optional: true}
          - {label: "CTA", name: "cta", widget: "string", optional: true}
          - {label: "Sluttext", name: "ending", widget: "markdown", optional: true}

      - file: "src/pages/nlr-trappan/index.md"
        label: "NLR-trappan"
        name: "nlr"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "nlr-page"}
          - {label: "Title", name: "title", widget: "string", optional: true}
          - {label: "Body", name: "body", widget: "markdown", optional: true}
