backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Featurebild", name: "img", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Meta Title", name: "metaTitle", widget: "string", required: false}
      - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
      - {label: "OG:image", name: "ogImage", widget: "image", required: false}

  - name: "quotes"
    label: "Citat"
    folder: "src/pages/quotes"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string", required: false}
      - {label: "Bild", name: "img", widget: "image", required: false}
      - {label: "Citat", name: "quote", widget: "text", required: false}
      - {label: "Taggar", name: "tags", widget: list}

  - name: "pages"
    label: "Pages"
    files:
      - name: "footer"
        label: "Footer"
        file: "src/pages/footer/index.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "footer"}
          - label: "Partners"
            name: "partners"
            widget: "list"
            required: false
            fields:
              - {label: "Name", name: "name", widget: "string", required: false}
              - {label: "Länk", name: "link", widget: "string", required: false}
      - name: "universal"
        label: "Startsida"
        file: "src/pages/index/index.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "start-page"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Topptitel", name: "title", widget: "string", required: false}
          - {label: "Subtitel", name: "subtitle", widget: "string", required: false}
          - {label: "introtext", name: "intro", widget: "string", required: false}
          - label: "Erbjudanden"
            name: "offers"
            widget: "list"
            required: false
            fields:
              - {label: "Bild", name: "img", widget: "image"}
              - {label: "Rubrik", name: "title", widget: "string", required: false}
              - {label: "CTA", name: "cta", widget: "string", required: false}
              - {label: "Länk", name: "link", widget: "string", required: false}
          - {label: "Coachtext", name: "coachText", widget: "string", required: false}
          - {label: "Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
          - {label: "OG:image", name: "ogImage", widget: "image", required: false}
      - file: "src/pages/privat/index.md"
        label: "Privat"
        name: "privat"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "privat-page"}
          - {label: "Topptitel", name: "title", widget: "string", required: false}
          - {label: "Introtext", name: "intro", widget: "markdown", required: false}
          - {label: "CTA", name: "cta", widget: "string", required: false}
          - {label: "Erbjudanderubrik", name: "offerTitle", widget: "string", required: false}
          - label: "Erbjudanden"
            name: "offers"
            widget: "list"
            required: false
            fields:
              - {label: "Rubrik", name: "title", widget: "string", required: false}
              - {label: "Text", name: "body", widget: "markdown", required: false}
              - {label: "Pris", name: "price", widget: "text", required: false}
              - {label: "Bild", name: "img", widget: "image", required: false}
          - {label: "Sluttext", name: "ending", widget: "markdown", required: false}
          - {label: "Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
          - {label: "OG:image", name: "ogImage", widget: "image", required: false}

      - file: "src/pages/foretag/index.md"
        label: "Företag"
        name: "foretag"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "privat-page"}
          - {label: "Topptitel", name: "title", widget: "string", required: false}
          - {label: "Introtext", name: "intro", widget: "markdown", required: false}
          - {label: "CTA", name: "cta", widget: "string", required: false}
          - {label: "Erbjudanderubrik", name: "offerTitle", widget: "string", required: false}
          - label: "Erbjudanden"
            name: "offers"
            widget: "list"
            required: false
            fields:
              - {label: "Rubrik", name: "title", widget: "string", required: false}
              - {label: "Text", name: "body", widget: "markdown", required: false}
              - {label: "Bild", name: "img", widget: "image", required: false}
          - {label: "Sluttext", name: "ending", widget: "markdown", required: false}
          - {label: "Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
          - {label: "OG:image", name: "ogImage", widget: "image", required: false}

      - file: "src/pages/coacher/index.md"
        label: "Coacher"
        name: "coacher"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "coach-page"}
          - {label: "Topptitel", name: "title", widget: "string"}
          - {label: "Introtext", name: "intro", widget: "text"}
          - label: "Coacher"
            name: "coaches"
            widget: "list"
            required: false
            fields:
              - {label: "Bild", name: "img", widget: "image", required: false}
              - {label: "Namn", name: "title", widget: "string", required: false}
              - {label: "USP", name: "usp", widget: "string", required: false}
              - {label: "Text", name: "text", widget: "markdown", required: false}
          - {label: "Sluttext", name: "ending", widget: "markdown", required: false}
          - {label: "CTA", name: "cta", widget: "string", required: false}
          - {label: "Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
          - {label: "OG:image", name: "ogImage", widget: "image", required: false}

      - file: "src/pages/kontakt/index.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Topptitel", name: "title", widget: "string", required: false}
          - {label: "Introtext", name: "intro", widget: "text", required: false}
          - label: "Formulär"
            name: "forms"
            widget: "list"
            required: false
            fields:
              - {label: "Namn", name: "name", widget: "string", required: false}
              - {label: "Placeholdertext", name: "placeholder", widget: "string", required: false}
              - {label: "Typ", name: "type", widget: 'select', options: ['text', 'email', 'number', 'tel', 'url', 'textarea'], required: false}
          - {label: "CTA", name: "cta", widget: "string", required: false}
          - {label: "Sluttext", name: "ending", widget: "markdown", required: false}
          - {label: "Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
          - {label: "OG:image", name: "ogImage", widget: "image", required: false}

      - file: "src/pages/nlr-trappan/index.md"
        label: "NLR-trappan"
        name: "nlr"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "nlr-page"}
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false}
          - {label: "Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
          - {label: "OG:image", name: "ogImage", widget: "image", required: false}

      - file: "src/pages/integritetspolicy/index.md"
        label: "Integritetspolicy"
        name: "integritetspolicy"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "nlr-page"}
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false}
          - {label: "Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "Meta Description", name: "metaDescription", widget: "string", required: false}
          - {label: "OG:image", name: "ogImage", widget: "image", required: false}
