backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)

media_folder: "assets"

collections: 
  - name: "pages"
    label: "Pages"
    files:
      - file: "static/content/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}